### ISSUE TITLE
Create demo web page based on cloudsim

### ISSUE THREAD

**Issue by k-okada** [tork-a/visualization_rwt#25]
visualization_rwt で何ができるか簡単に紹介できるデモサイトを作りたい。

clodusimのシミュレーションを前提にしてもよいし,
pr1040は常に動いている、という前提でデモを作ってもいい気がします。

作り方の方針を教えてくれれば、僕が勉強がてらやってみたいです。

**Comment by garaemon** [comment]
作りましょう

できることはグラフのプロット、robot_monitor web版、image_view web版, moveitクライアントでしょうか。

> 作り方の方針を教えてくれれば、僕が勉強がてらやってみたいです。

とりあえずgazeboが常に走ってるサーバーを設定するのが良いと思います。
もしくは、rosbagでしょうか

**Comment by k-okada** [comment]
http://54.197.81.122/cloudsim/inside/cgi-bin/console
でgazeboを立ち上げました，
http://107.21.29.133:8080/
で，web でシミュレーションがみえます．

上のconsole の画面で，routerのDownload Keysをおして，落としてきたzipを展開してルートで
    LANG=C start_vpn.bash
として，ros.bash をsource して rostopic すろとトピックが見えます．これでいいのかな．

**Comment by garaemon** [comment]
お、いいっぽいですね。

ROSの走ってる計算機で

``` xml
<launch>
  <node pkg="roswww" type="webserver.py" name="roswww">
  </node>
  <include file="$(find rosbridge_server)/launch/rosbridge_websocket.launch">
    <arg name="port" value="8888" />
  </include>
</launch>
```

を走らせると、`:8888`でみれるようになります。

フロントエンドは、gh-pagesでやるか、visualization_rwt_demoみたいなパッケージをつくるかどうかというところですが...
http://hisasann.com/housetect/2012/02/githubgh-pages.html

普通にデモ用のパッケージを作るのが楽そうですね。

**Comment by 130s** [comment]
+1 for creating a frontend demo package. Ticketed #29.

I've also started working on this, aiming to more focus on each robot we're dealing with ([related](https://github.com/start-jsk/denso/issues/27)), which as always will come fully documented if I succeed :)

Changed title to more specific one and close this since it looks like the demo worked with `cloudsim` (though now I can't see the demo site running).
